# Generated by Django 3.2.7 on 2022-04-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_student',
            field=models.CharField(max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
