# Generated by Django 3.2.7 on 2022-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_student',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
